FROM arm32v7/debian:bullseye

RUN apt-get update \
    && apt-get install -y --no-install-recommends libxml2 libxslt1.1 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /out && \
    for lib in \
        /usr/lib/arm-linux-gnueabihf/libxml2.so.2 \
        /usr/lib/arm-linux-gnueabihf/libxslt.so.1 \
        /usr/lib/arm-linux-gnueabihf/libexslt.so.0 \
        /usr/lib/arm-linux-gnueabihf/libgcrypt.so.20 \
        /usr/lib/arm-linux-gnueabihf/libgpg-error.so.0 \
        /usr/lib/arm-linux-gnueabihf/libicuuc.so.67 \
        /usr/lib/arm-linux-gnueabihf/libicudata.so.67; \
    do \
        if [ -e "$lib" ]; then cp -L "$lib" /out/; fi; \
    done
